### ISSUE TITLE
Why Gulp over Grunt?

### ISSUE THREAD

**Issue by ghost** [RookieOne/learning-gulp-book#1]
Sorry this isn't really an issue, but more of a question:

Why Gulp over Grunt?

I have played around with Grunt the past couple of weeks and have been curious if Gulp is better? Is the grass _truly_ greener on the other side of the fence?

**Comment by RookieOne** [comment]
Hey Max.

I like Gulp > Grunt because of the different way it does builds. Grunt is
about configuring plugins and knowing what options to turn on.

Gulp is more like programming node streams. Since I am programmer, I find
that model easier for me to grok and customize.

Besides that, they are both fantastic tools and will serve any project
well. It is more about how you like to create + customize your builds.

JB

**Comment by ghost** [comment]
Ah I see. Thanks for the input and clarifying the difference between the
two!
- Max M.
